### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by cagaha** [WangYuxuan93/DepAttacker#2]
作者你好，我不太了解数据集怎么弄的，所以代码还是没跑起来，希望和您交流一下，可以加我微G18260063086，或者留下您的联系方式吗

**Comment by Zhi-lin** [comment]
可以发邮件，微信不常用。 ***@***.***













在 2021-10-26 19:36:15，"cagaha" ***@***.***> 写道：

作者你好，我不太了解数据集怎么弄的，所以代码还是没跑起来，希望和您交流一下，可以加我微G18260063086，或者留下您的联系方式吗

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zhi-lin** [comment]
你报错的问题是数据格式。输入的数据格式conllu的格式。

**Comment by cagaha** [comment]
> 你报错的问题是数据格式。输入的数据格式conllu的格式。

你好，生成完候选词在用preprocess处理的时候好像缺少很多文件，比如word_embeddings_file = "paragram.npy"
        word_list_file = "wordlist.pickle"
        nn_matrix_file = "nn.npy"
        cos_sim_file = "cos_sim.p"，方便发我一份完整的代码吗（报考代码和各种文件）

**Comment by Zhi-lin** [comment]
生成离线文件的脚本在adversary/scripts里面

**Comment by Zhi-lin** [comment]
build_embed_nn.py是用来调整词向量，得到的结果就是你要的paragram.npy, worklist.pickle, nn.npy cos_sim.p等。如果有问题，还请先阅读readme文件, 由于文字表述可能引起歧义，如果有模糊的地方，欢迎提issue。  参考readme里面的这句话“adjust the embedding according to <https://github.com/nmrksic/counter -fitting> . Maybe,you need to compute the similarity Matrix using compute_nn.sh and merge_nn.sh”

**Comment by Zhi-lin** [comment]
我上传了你所需要的这些文件,对于glove（英文）的词向量调整结果在resource/paragramcf的文件夹里面。对于giga（中文）的词向量在resource/giga-zh.counter_filterd.nn
